# Setup
title:               Lifelong Study
tagline:             'Test1A'
description:         'test-1a'
url:                 https://fallingsnow2020.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              FallingSnow2020
  url:               https://fallingsnow2020.github.io/
  email:             robertvw20@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
